name = "LinearFractional"
uuid = "31851ddc-f9b7-5097-a470-69ef907d7682"
version = "0.6.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
julia = "^1.1"
JuMP = "^0.19"

[extras]
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"

[targets]
test = ["Clp"]
