name = "LinearFractional"
uuid = "31851ddc-f9b7-5097-a470-69ef907d7682"
version = "0.7.7"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
JuMP = "1.13 - 1.22.1"
MacroTools = "^0.5"
MathOptInterface = "^1"
julia = "^1.6"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Clp", "Cbc", "ECOS", "Test", "LinearAlgebra"]
